services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  doctor-service:
    build: ./doctor-service
    ports:
      - "5002:5002"
    environment:
     - NODE_ENV=production
     - PORT=5002
     - SERVICE_NAME=doctor-service
     - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
  
  appointment-service:
    build: ./appointment-service
    ports: 
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DOCTOR_SERVICE_URL=http://doctor-service:5002
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - doctor-service
      - rabbitmq
  
  notification-service:
    build: ./notification-service
    environment:
      - NODE_ENV=production
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
  
  records-service:
    build: ./records-service
    environment:
      - NODE_ENV=production
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq

networks:
  default:
    name: microservices-network